<?php include 'inc/header.phtml'; ?>
<body class="main">
<?php if (isset($username)): ?>
<?php include 'inc/nav.phtml'; ?>
<?php endif; ?>
    <div class="container-fluid">
        <div class="col-md-12 main-dashboard">
            <h1 class="error"><?=$message; ?></h1>
        </div>
    </div>
    <footer class="footer">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include 'inc/footer.phtml'; ?>