<?php if (isset($fluidNav)): ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    </div>
<!-- Footer //-->
    <footer class="footer">
        <div class="text-muted">&copy; <?=date('Y'); ?> <?=$application_title; ?>. All Rights Reserved.</div>
    </footer>
    <div id="saved" class="alert alert-success" role="alert"<?=(isset($saved) ? ' data-saved="1"' : null); ?>>Saved</div>
    <div id="removed" class="alert alert-danger" role="alert"<?=(isset($removed) ? ' data-removed="1"' : null); ?>>Removed</div>
    <div id="expired" class="alert alert-danger" role="alert"<?=(isset($expired) ? ' data-expired="1"' : null); ?>>Session Expired</div>
    <div id="failed" class="alert alert-danger" role="alert"<?=(isset($failed) ? ' data-failed="1"' : null); ?>>Login Failed</div>
<script src="//code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="/assets/js/pop.js"></script>
<script src="/assets/js/scripts.js"></script>
</body>

</html>