<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?=$title; ?> : <?=$application_title; ?></title>

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,700,700italic,900,900italic" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> //-->
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/styles.css" />

</head>

<body>
<?php if (isset($user)): ?>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><?=$application_title; ?></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
<?=$popNav; ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/profile" class="profile-link"><?=$user->username; ?></a></li>
                    <li><a href="/logout" class="logout-link">Logout</a></li>
                </ul>
<?php if (null !== $user->last_login): ?>
                <div class="user-header pull-right">
                    Last: <span><?=date('M j Y, H:i', strtotime($user->last_login)); ?></span>
<?php if (null !== $user->last_ip): ?>
                    <span>[<?=$user->last_ip; ?>]</span>
<?php endif; ?>
                </div>
<?php endif; ?>
            </div>
        </div>
    </nav>
<?php endif; ?>
    <div class="container-fluid">
<?php if (isset($sideNav)): ?>
        <div class="row">
            <div class="col-sm-2 col-md-1 sidebar">
<?=$sideNav; ?>
            </div>
            <div class="col-sm-10 col-sm-offset-2 col-md-11 col-md-offset-1 main">
<?php endif; ?>
