<?php include 'inc/header.phtml'; ?>
<body class="main">
<?php include 'inc/nav.phtml'; ?>
    <div class="container-fluid">
        <div class="col-md-12 main-dashboard">
            <h1 class="dashboard-header">Dashboard</h1>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1001</td>
                    <td>Test Person</td>
                    <td>123 Main St.</td>
                    <td>New Orleans</td>
                    <td>LA</td>
                    <td>70124</td>
                </tr>
                <tr>
                    <td>1002</td>
                    <td>Test Person</td>
                    <td>123 Main St.</td>
                    <td>New Orleans</td>
                    <td>LA</td>
                    <td>70124</td>
                </tr>
                <tr>
                    <td>1003</td>
                    <td>Test Person</td>
                    <td>123 Main St.</td>
                    <td>New Orleans</td>
                    <td>LA</td>
                    <td>70124</td>
                </tr>
                <tr>
                    <td>1004</td>
                    <td>Test Person</td>
                    <td>123 Main St.</td>
                    <td>New Orleans</td>
                    <td>LA</td>
                    <td>70124</td>
                </tr>
                <tr>
                    <td>1005</td>
                    <td>Test Person</td>
                    <td>123 Main St.</td>
                    <td>New Orleans</td>
                    <td>LA</td>
                    <td>70124</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <footer class="footer">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include 'inc/footer.phtml'; ?>