<?php include 'inc/header.phtml'; ?>
<body class="login">
    <div class="login-pad"></div>
    <div class="login-div">
<?=$form; ?>
<?php if (isset($error)): ?>
        <h5 class="error"><?=$error; ?></h5>
<?php endif; ?>
    </div>
    <footer class="footer login-footer">
        <div>Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include 'inc/footer.phtml'; ?>