<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?=$title; ?></title>

    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,700,700italic,900,900italic" />
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/pop.css" />

</head>
<body class="main main-side-nav">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top top-nav">
        <a class="home" href="/">Pop Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="nav navbar-nav navbar-right user-nav">
            <li><a href="#" title="Messages"><i class="material-icons">message</i></a><span class="msg-num"><span>3</span></span></li>
            <li><a href="#" title="Profile"><i class="material-icons">account_box</i></a></li>
            <li><a href="/logout?revoke=1" title="Logout"><i class="material-icons">exit_to_app</i></a></li>
        </ul>
        <div class="logged-in">
            <h5><a href="#"><?=$username; ?></a></h5>
            <p><?=date('M j, Y g:i A'); ?></p>
        </div>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto main-nav">
                <li>
                    <a href="/orders" title="Orders"><i class="material-icons icon-sm">edit</i><span>Orders</span></a>
                    <ul>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Create</a></li>
                        <li><a href="#">Submit</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" title="Services"><i class="fa fa-gears"></i><span>Services</span></a>
                    <ul>
                        <li>
                            <a href="#">Clients</a>
                            <ul>
                                <li><a href="#">Sub Menu</a></li>
                                <li><a href="#">Another Menu</a></li>
                                <li><a href="#">One More Menu</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Vendors</a></li>
                    </ul>
                </li>
                <li><a href="#" title="Reports"><i class="material-icons">timeline</i><span>Reports</span></a></li>
                <li><a href="#" title="Billing"><i class="material-icons">attach_money</i><span>Billing</span></a></li>
                <li><a href="#" title="Tools"><i class="material-icons icon-sm">build</i><span>Tools</span></a></li>
                <li><a href="#" title="Users"><i class="material-icons">group</i><span>Users</span></a></li>
                <li><a href="#" title="Admin"><i class="material-icons icon-sm">verified_user</i><span>Admin</span></a></li>
            </ul>
        </div>
    </nav><div class="clearfix"></div>
    <div id="sidebar-nav" class="sidebar-nav">
        <ul class="side-nav">
            <li><a href="#" title="Overview" class="nav-on"><i class="material-icons">web</i><span>Overview</span></a></li>
            <li><a href="#" title="Contacts"><i class="material-icons">perm_contact_calendar</i><span class="nav-top-pad">Contacts</a></li>
            <li><a href="#" title="Documents"><i class="material-icons">insert_drive_file</i><span class="nav-top-pad">Documents</span></a></li>
        </ul>
        <h5>Order<span> Data</span></h5>
        <ul class="side-nav">
            <li><a href="#" title="Banking"><i class="material-icons">account_balance</i><span>Banking</span></a></li>
            <li><a href="#" title="Links"><i class="fa fa-chain fa-3x"></i><span>Links</span></a></li>
            <li><a href="#" title="Judgments"><i class="fa fa-gavel fa-3x"></i><span>Judgments</span></a></li>
            <li><a href="#" title="Requirements"><i class="material-icons">error_outline</i><span>Requirements</span></a></li>
            <li><a href="#" title="Restrictions"><i class="material-icons">block</i><span>Restrictions</span></a></li>
            <li>
                <a href="#" title="Other"><i class="material-icons">arrow_forward</i><span>Other</span></a>
                <ul>
                    <li><a href="#">Deeds</a></li>
                    <li><a href="#">Foreclosures</a></li>
                    <li><a href="#">Terms</a></li>
                </ul>
            </li>
            <li><a href="#" title="Taxes"><i class="material-icons">local_atm</i><span>Taxes</span></a></li>
            <li><a href="#" title="Legal"><i class="material-icons">format_align_left</i><span>Legal Description</span></a></li>
        </ul>
        <h5><span>Order </span>Info</h5>
        <ul class="side-nav">
            <li><a href="#" title="Status"><i class="material-icons">schedule</i><span>Status</span></a></li>
            <li><a href="#" title="Expenses"><i class="material-icons">monetization_on</i><span>Expenses</span></a></li>
        </ul>
        <a href="#" id="sub-nav-toggle" class="sub-nav-toggle-left"></a>
    </div>
    <div id="main-content" class="main-content">
        <h2>12345678 <span>[P-9876]</span></h2>
        <ul class="nav nav-tabs overview-nav">
            <li class="nav-item"><a href="#" title="Client" class="nav-link active"><i class="material-icons">person</i><span>Client</span></a></li>
            <li class="nav-item"><a href="#" title="Assignment" class="nav-link"><i class="material-icons">assignment_ind</i><span>Assignment</span></a></li>
            <li class="nav-item"><a href="#" title="Notes" class="nav-link"><i class="material-icons">speaker_notes</i><span>Notes</span></a></li>
        </ul>
    </div>
    <footer class="footer footer-side">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
    <script src="/assets/js/jquery-3.2.1.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/pop.js"></script>
</body>

</html>