<?php include __DIR__ . '/../inc/header.phtml'; ?>
<body class="main main-side-nav">
<?php include __DIR__ . '/../inc/nav.phtml'; ?>
    <div class="clearfix"></div>
    <div id="sidebar-nav" class="sidebar-nav">
        <ul class="side-nav">
            <li><a href="#" title="Overview" class="nav-on"><i class="material-icons">web</i><span>Overview</span></a></li>
            <li><a href="#" title="Contacts"><i class="material-icons">perm_contact_calendar</i><span class="nav-top-pad">Contacts</a></li>
            <li><a href="#" title="Documents"><i class="material-icons">insert_drive_file</i><span class="nav-top-pad">Documents</span></a></li>
        </ul>
        <h5>Order<span> Data</span></h5>
        <ul class="side-nav">
            <li><a href="#" title="Banking"><i class="material-icons">account_balance</i><span>Banking</span></a></li>
            <li><a href="#" title="Links"><i class="fa fa-chain fa-3x"></i><span>Links</span></a></li>
            <li><a href="#" title="Judgments"><i class="fa fa-gavel fa-3x"></i><span>Judgments</span></a></li>
            <li><a href="#" title="Requirements"><i class="material-icons">error_outline</i><span>Requirements</span></a></li>
            <li><a href="#" title="Restrictions"><i class="material-icons">block</i><span>Restrictions</span></a></li>
            <li>
                <a href="#" title="Other"><i class="material-icons">arrow_forward</i><span>Other</span></a>
                <ul>
                    <li><a href="#">Deeds</a></li>
                    <li><a href="#">Foreclosures</a></li>
                    <li><a href="#">Terms</a></li>
                </ul>
            </li>
            <li><a href="#" title="Taxes"><i class="material-icons">local_atm</i><span>Taxes</span></a></li>
            <li><a href="#" title="Legal"><i class="material-icons">format_align_left</i><span>Legal Description</span></a></li>
        </ul>
        <h5><span>Order </span>Info</h5>
        <ul class="side-nav">
            <li><a href="#" title="Status"><i class="material-icons">schedule</i><span>Status</span></a></li>
            <li><a href="#" title="Expenses"><i class="material-icons">monetization_on</i><span>Expenses</span></a></li>
        </ul>
        <a href="#" id="sub-nav-toggle" class="sub-nav-toggle-left"></a>
    </div>
    <div id="main-content" class="main-content">
        <h2><i class="material-icons">edit</i> 12345678 <span>[P-9876]</span></h2>
        <ul class="nav nav-tabs overview-nav">
            <li class="nav-item"><a href="#" title="Client" class="nav-link active"><i class="material-icons">person</i><span>Client</span></a></li>
            <li class="nav-item"><a href="#" title="Assignment" class="nav-link"><i class="material-icons">assignment_ind</i><span>Assignment</span></a></li>
            <li class="nav-item"><a href="#" title="Notes" class="nav-link"><i class="material-icons">speaker_notes</i><span>Notes</span></a></li>
        </ul>
        <br />
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat tortor diam, eu ullamcorper lacus efficitur id. Cras sodales est eu finibus laoreet. Nulla imperdiet pellentesque ex, non rutrum sem iaculis quis. Duis eget leo urna. Integer sodales, massa sed feugiat dignissim, risus enim venenatis augue, non mollis dui nibh in turpis. Sed ac lorem commodo, efficitur sem ac, maximus odio. Nam lorem ante, tempor ut orci vel, malesuada cursus velit. Morbi sem ante, hendrerit quis sapien vel, pulvinar ultrices nulla. Duis arcu ligula, congue id magna ut, efficitur sodales mauris.</p>
        <p>Aliquam nec sollicitudin ante, sollicitudin tempus orci. Pellentesque fringilla, dui eu sodales tincidunt, nisi risus rhoncus magna, non ullamcorper augue urna ut justo. Donec vitae augue venenatis dui scelerisque ultricies eu non arcu. Morbi tempus, purus id cursus bibendum, risus orci fermentum augue, nec fermentum dolor ex ut magna. Nulla facilisi. Proin a dui rhoncus, mattis purus eu, vestibulum lacus. Nam quis urna pharetra, rutrum ipsum a, aliquet elit. Etiam gravida id magna vitae accumsan. Maecenas aliquam ex non arcu fermentum vulputate nec sit amet nunc. Integer tempor lacus a gravida mollis. Donec rhoncus imperdiet nisl in placerat. Vestibulum viverra rhoncus purus sed aliquam. Vivamus rhoncus maximus sem quis ultricies. Duis dignissim, turpis vel tristique efficitur, odio quam pellentesque ex, vitae vestibulum tortor dolor faucibus diam. Praesent egestas finibus accumsan. Nunc vestibulum rutrum orci, in porta massa sagittis in.</p>
        <p>Donec vestibulum libero in semper sollicitudin. Donec sit amet felis tempus, suscipit felis in, tincidunt erat. Nunc mollis nec nisl sit amet dictum. Cras vel est eu lectus tempor ullamcorper ac eget orci. In lorem nulla, finibus eu consequat non, ultrices non augue. Curabitur pellentesque in nisi at semper. Aliquam leo arcu, sodales volutpat massa et, varius dapibus nulla.</p>
    </div>
    <footer class="footer footer-side">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>