<?php include __DIR__ . '/../header.phtml'; ?>

    <div class="container-fluid">
        <h1 class="roles-header"><?=$title; ?></h1>
<?php if (null !== $pages): ?>
        <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
        <nav id="sub-nav">
            <nav><a class="btn-sm btn-info" href="/roles/add">+ Add</a></nav>
        </nav>
        <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
                <thead>
                <tr>
                    <th class="col-md-1 text-center"><a href="/roles?sort=id<?=(($queryString != '') ? '&' . $queryString : '');?>">#</a></th>
                    <th><a href="/roles?sort=name<?=(($queryString != '') ? '&' . $queryString : '');?>">Name</a></th>
                    <th class="text-center">Edit</th>
                    <th class="col-md-1 text-center"><input type="checkbox" name="check_all" id="checkAll" data-name="rm_roles" value="" /></th>
                </tr>
                </thead>
                <tbody>
<?php foreach ($roles as $r): ?>
                <tr>
                    <td class="text-center"><?=$r->id; ?></td>
                    <td><?=$r->name; ?></td>
                    <td class="text-center"><a class="edit-link" href="/roles/edit/<?=$r->id; ?>">Edit</a></td>
                    <td class="text-center"><input type="checkbox" name="rm_roles[]" value="<?=$r->id; ?>" /></td>
                </tr>
<?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

<?php include __DIR__ . '/../footer.phtml'; ?>