#!/usr/bin/php
<?php
/**
 * Pop Bootstrap Console Application
 */

$autoloader = include __DIR__ . '/../vendor/autoload.php';

try {
    $app = new Pop\Application($autoloader, include __DIR__ . '/../app/config/app.console.php');
    $app->register(new App\Module());
    $app->run();
} catch (\Exception $exception) {
    $app = new App\Module();
    $app->cliError($exception);
}