<?php include __DIR__ . '/../inc/header.phtml'; ?>
<body class="main">
<?php include __DIR__ . '/../inc/nav.phtml'; ?>
    <div class="container-fluid">
        <div class="col-md-12 main-dashboard">
            <h1 class="users-header"><i class="material-icons">group</i><?=$title; ?></h1>
            <nav class="sub-nav">
                <a class="btn btn-info btn-sm text-uppercase" href="/users/add" title="Add User"><i class="material-icons">person_add</i></a>
                <a class="btn btn-info btn-sm text-uppercase" href="/users" title="Back"><i class="material-icons">chevron_left</i></a>
            </nav>
<?=$form; ?>
        </div>
    </div>
    <footer class="footer">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>