<?php include __DIR__ . '/../inc/header.phtml'; ?>
<body class="main">
<?php include __DIR__ . '/../inc/nav.phtml'; ?>
    <div class="container-fluid">
        <div class="col-md-12 main-dashboard">
            <a class="btn btn-info btn-sm text-uppercase pull-right add-user-btn" href="/users/add"><i class="material-icons">person_add</i></a>
            <h1 class="users-header"><i class="material-icons">group</i><?=$title; ?></h1>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>#</th>
                    <th>Username</th>
                    <th>Active</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
<?php if (isset($users) && (count($users) > 0)): ?>
<?php foreach ($users as $user): ?>
                <tr>
                    <td><a href="/users/<?=$user->id; ?>"><i class="material-icons">create</i></a></td>
                    <td><?=$user->id; ?></td>
                    <td><?=$user->username; ?></td>
                    <td><?=($user->active) ? 'Yes' : 'No'; ?></td>
                    <td><input type="checkbox" name="rm_users" value="<?=$user->id; ?>" /></td>
                </tr>
<?php endforeach; ?>
<?php else: ?>
                <tr>
                    <td colspan="5"><p>There are currently no users.</p></td>
                </tr>
<?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <footer class="footer">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>