<?php include __DIR__ . '/../header.phtml'; ?>

    <div class="container-fluid">
        <h1 class="users-header"><?=$title; ?><?php if (isset($roleId) && isset($roles) && isset($roles[$roleId])): ?> : <?=$roles[$roleId]; ?><?php endif; ?></h1>
<?php if (null !== $pages): ?>
        <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
        <nav id="sub-nav">
            <nav><a class="btn-sm btn-info" href="/users/add<?php if (null !== $roleId): ?><?='/' . $roleId; ?><?php endif; ?>">+ Add</a></nav>
        </nav>
<?php if (count($users) > 0): ?>
        <div class="table-responsive">
            <form id="users-form" action="/users/process" method="post">
            <table class="table table-striped table-hover table-condensed">
                <thead>
                <tr>
                    <th class="col-md-1 text-center"><a href="/users<?=((null !== $roleId) ? '/' . $roleId : null) . '?sort=id' . (($queryString != '') ? '&' . $queryString : '');?>">#</a></th>
                    <th><a href="/users<?=((null !== $roleId) ? '/' . $roleId : null) . '?sort=username' . (($queryString != '') ? '&' . $queryString : '');?>">Username</a></th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Verified</th>
                    <th class="text-center">Edit</th>
                    <th class="col-md-1 text-center"><input type="checkbox" name="check_all" id="checkAll" data-name="process_users" value="" /></th>
                </tr>
                </thead>
                <tbody>
<?php foreach ($users as $u): ?>
                <tr>
                    <td class="text-center"><?=$u->id; ?></td>
                    <td><?=$u->username; ?></td>
                    <td><?=$u->email; ?></td>
                    <td><?=($u->active) ? 'Yes' : 'No'; ?></td>
                    <td><?=($u->verified) ? 'Yes' : 'No'; ?></td>
                    <td class="text-center"><a class="edit-link" href="/users/edit/<?=$u->id; ?>">Edit</a></td>
                    <td class="text-center"><input type="checkbox" name="process_users[]" value="<?=$u->id; ?>" /></td>
                </tr>
<?php endforeach; ?>
                </tbody>
            </table>
            <div id="form-footer">
                <select id="user_process_action" name="user_process_action">
                    <option value="1">Activate</option>
                    <option value="0">Deactivate</option>
                    <option value="-1">Remove</option>
                </select>
                <input type="hidden" name="role_id" value="<?php if (null !== $roleId): echo $roleId; else: echo '0'; endif; ?>" />
                <input type="submit" name="submit" class="btn btn-md btn-primary text-uppercase" value="Process" />
            </div>
            </form>
        </div>
<?php else: ?>
        <p>There are current no users.</p>
<?php endif; ?>
    </div>

<?php include __DIR__ . '/../footer.phtml'; ?>