<?php include __DIR__ . '/../inc/header.phtml'; ?>
<body class="main">
<?php include __DIR__ . '/../inc/nav.phtml'; ?>
    <div class="container-fluid">
        <div class="col-md-12 main-dashboard">
            <h1 class="users-header"><i class="material-icons">group</i><?=$title; ?></h1>
            <nav class="sub-nav">
                <a class="btn btn-info btn-sm text-uppercase" href="/users/add" title="Add User"><i class="material-icons">person_add</i></a>
            </nav>
<?php if (isset($users) && (count($users) > 0)): ?>
            <form action="/users/remove" method="post">
<?php endif; ?>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th class="table-sm">#</th>
                    <th>Username</th>
                    <th class="table-sm">Active</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
<?php if (isset($users) && (count($users) > 0)): ?>
<?php foreach ($users as $user): ?>
                <tr>
                    <td><a class="gray-link" href="/users/<?=$user->id; ?>"><i class="material-icons edit-icon-md">edit</i></a></td>
                    <td class="table-sm"><?=$user->id; ?></td>
                    <td><?=$user->username; ?></td>
                    <td class="table-sm"><?=($user->active) ? 'Yes' : 'No'; ?></td>
                    <td><?php if ($userId != $user->id): ?><input type="checkbox" name="rm_users[]" value="<?=$user->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
                </tr>
<?php endforeach; ?>
<?php else: ?>
                <tr>
                    <td colspan="5"><p>There are currently no users.</p></td>
                </tr>
<?php endif; ?>
                </tbody>
            </table>
<?php if (isset($users) && (count($users) > 0)): ?>
            <div class="form-footer">
                <input type="submit" name="submit" class="btn btn-md btn-primary text-uppercase" value="Remove" />
            </div>
            </form>
<?php endif; ?>
        </div>
    </div>
    <footer class="footer">
        <div class="text-muted">Pop Boostrap. <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a>.</div>
    </footer>
<?php include __DIR__ . '/../inc/footer.phtml'; ?>